version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.11.1

      # Specify service dependencies here if necessary
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: trufflesuite/ganache-cli
        command: ganache-cli -i 1234 -e 100000000000 -l 4700038

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test # triggers truffle test
